"""Add badge_colors field to character_layouts

Revision ID: 006
Revises: 9c5f8cc9b5a4
Create Date: 2025-11-26 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '006'
down_revision = '9c5f8cc9b5a4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('character_layouts', sa.Column('badge_colors', postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default='[]'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('character_layouts', 'badge_colors')
    # ### end Alembic commands ###
