"""Add image position offset fields to character_layouts

Revision ID: 008
Revises: 007
Create Date: 2025-11-27 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '008'
down_revision = '007'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('character_layouts', sa.Column('background_image_offset_x', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('character_layouts', sa.Column('background_image_offset_y', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('character_layouts', 'background_image_offset_y')
    op.drop_column('character_layouts', 'background_image_offset_x')
    # ### end Alembic commands ###
