"""Add background image offset fields to characters

Revision ID: 010
Revises: 009
Create Date: 2025-11-29 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '010'
down_revision = '009'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('characters', sa.Column('background_image_offset_x', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('characters', sa.Column('background_image_offset_y', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('characters', 'background_image_offset_y')
    op.drop_column('characters', 'background_image_offset_x')
    # ### end Alembic commands ###
