"""Add character card redesign fields: card_type, stats_config, image settings

Revision ID: 9c5f8cc9b5a4
Revises: 005
Create Date: 2025-11-25 19:04:38.361322

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9c5f8cc9b5a4'
down_revision = '005'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('campaigns', 'owner_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint('campaigns_slug_key', 'campaigns', type_='unique')
    op.drop_constraint('fk_campaigns_owner_id_users_id', 'campaigns', type_='foreignkey')
    op.create_foreign_key(None, 'campaigns', 'users', ['owner_id'], ['id'])
    op.add_column('character_layouts', sa.Column('card_type', sa.String(length=20), nullable=False))
    op.add_column('character_layouts', sa.Column('stats_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.add_column('character_layouts', sa.Column('image_width_percent', sa.Integer(), nullable=False))
    op.add_column('character_layouts', sa.Column('image_aspect_ratio', sa.String(length=20), nullable=False))
    op.add_column('character_layouts', sa.Column('background_image_url', sa.String(length=500), nullable=True))
    op.drop_index('idx_character_layouts_campaign', table_name='character_layouts')
    op.drop_index('idx_character_layouts_is_default', table_name='character_layouts')
    op.create_index(op.f('ix_character_layouts_campaign_id'), 'character_layouts', ['campaign_id'], unique=False)
    op.drop_index('idx_characters_campaign', table_name='characters')
    op.drop_index('idx_characters_slug', table_name='characters')
    op.drop_index('idx_episodes_campaign', table_name='episodes')
    op.drop_index('idx_episodes_number', table_name='episodes')
    op.drop_index('idx_episodes_slug', table_name='episodes')
    op.drop_index('idx_events_episode', table_name='events')
    op.drop_index('idx_events_type', table_name='events')
    op.create_index(op.f('ix_events_episode_id'), 'events', ['episode_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_events_episode_id'), table_name='events')
    op.create_index('idx_events_type', 'events', ['event_type'], unique=False)
    op.create_index('idx_events_episode', 'events', ['episode_id'], unique=False)
    op.create_index('idx_episodes_slug', 'episodes', ['slug'], unique=False)
    op.create_index('idx_episodes_number', 'episodes', ['episode_number'], unique=False)
    op.create_index('idx_episodes_campaign', 'episodes', ['campaign_id'], unique=False)
    op.create_index('idx_characters_slug', 'characters', ['slug'], unique=False)
    op.create_index('idx_characters_campaign', 'characters', ['campaign_id'], unique=False)
    op.drop_index(op.f('ix_character_layouts_campaign_id'), table_name='character_layouts')
    op.create_index('idx_character_layouts_is_default', 'character_layouts', ['is_default'], unique=False)
    op.create_index('idx_character_layouts_campaign', 'character_layouts', ['campaign_id'], unique=False)
    op.drop_column('character_layouts', 'background_image_url')
    op.drop_column('character_layouts', 'image_aspect_ratio')
    op.drop_column('character_layouts', 'image_width_percent')
    op.drop_column('character_layouts', 'stats_config')
    op.drop_column('character_layouts', 'card_type')
    op.drop_constraint(None, 'campaigns', type_='foreignkey')
    op.create_foreign_key('fk_campaigns_owner_id_users_id', 'campaigns', 'users', ['owner_id'], ['id'], ondelete='CASCADE')
    op.create_unique_constraint('campaigns_slug_key', 'campaigns', ['slug'])
    op.alter_column('campaigns', 'owner_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###
